[package]
name = "solana-rpc-tower"
version = "0.4.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
futures = "0.3"
reqwest = "0.11"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
solana-client = "2"
solana-rpc-client = "2"
solana-rpc-client-api = "2"
solana-sdk = "2"
solana-version = "2"
tokio = "1"
tower = { version = ">=0.5", features = ["full"] }
tracing = "0"

[dev-dependencies]
crossbeam-channel = "0.5"
jsonrpc-core = "18.0.0"
jsonrpc-http-server = "18.0.0"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
